- name: install and run nginx
  hosts: web
  become: yes # equal to -b in adhoc command become root
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest # it will install latest version--> absent will remove
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started  
      enabled: yes
