- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print information
    vars:
      timings: "07:15AM IST"
    ansible.builtin.debug: # This Task is not overriding any variable
      msg: "Hi, we are learning {{Course}} from trainer {{Trainer}}, Duration is {{Duration}} Timings are: {{timings}}"    